class WordBank:
    AUTHOR_KWS = {
        "we",
        "us",
        "our",
        "this article",
        "this paper",
        "this work",
        "this study",
        "this project",
    }

    NOVELTY_KWS = {
        "augment",
        "categorise",
        "categorize",
        "contrast",
        "demonstrate",
        "develop",
        "differ",
        "emphasize",
        "explore",
        "extend",
        "extend",
        "first",
        "formalize",
        "hypothesize",
        "investigate",
        "motivate",
        "new",
        "novel",
        "posit",
        "propose",
        "rethink",
        "solve",
        "speculate",
        "summarize",
        "uncover",
    }

    CONTRIBUTION_KWS = {"contribution", "contributions", "contribute"}

    RESULT_KWS = {
        "achieve",
        "demonstrate",
        "exceed",
        "find",
        "highlight",
        "observe",
        "obtain",
        "outperform",
        "reveal",
        "see",
        "significant",
        "show",
        "surpass",
        "result",
        "takeaway",
        "verify",
        "sota",
        "state-of-the-art",
        "improve",
    }

    OBJECTIVE_KWS = {"aim", "goal", "purpose", "motivation", "objective"}

    METHOD_KWS = {
        "add",
        "adopt",
        "analyze",
        "apply",
        "approximate",
        "assume",
        "believe",
        "boost",
        "build",
        "choose",
        "collect",
        "combine",
        "compare",
        "compute",
        "conduct",
        "confirm",
        "consider",
        "construct",
        "control",
        "convert",
        "create",
        "define",
        "denoise",
        "design",
        "divide",
        "embed",
        "employ",
        "encode",
        "encourage",
        "establish",
        "evaluate",
        "experiment",
        "explore",
        "extract",
        "favor",
        "filter",
        "fine-tune",
        "finetune",
        "focus",
        "follow",
        "force",
        "form",
        "formalize",
        "formulate",
        "generate",
        "implement",
        "initialize",
        "is",
        "identify",
        "limit",
        "measure",
        "mitigate",
        "modify",
        "multiply",
        "omit",
        "optimize",
        "perform",
        "predict",
        "present",
        "pretrain",
        "produce",
        "provide",
        "recommend",
        "reduce",
        "regularize",
        "reject",
        "remove",
        "replace",
        "retrieve",
        "sample",
        "simulate",
        "split",
        "study",
        "summarize",
        "tackle",
        "take",
        "track",
        "train",
        "transform",
        "update",
        "use",
        "utilize",
    }
